@echo off
echo Redemarrage du serveur API...
echo Arret des processus Node.js existants...
taskkill /f /im node.exe 2>nul
timeout /t 2 /nobreak >nul
echo Demarrage du serveur API sur le port 3020...
node server.js
