name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        cache: true

    - name: Clean and get dependencies
      run: |
        flutter clean
        flutter pub get

    - name: Build APK (no-shrink for compatibility)
      run: flutter build apk --release --no-shrink

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiforama-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
