name: Docker Flutter APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/cirruslabs/flutter:stable
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          flutter --version
          flutter doctor -v
          uname -a
          echo "Working directory:"
          pwd
          ls -la

      - name: Flutter setup
        run: |
          flutter clean
          flutter pub get

      - name: Prepare Android build
        run: |
          cd android
          chmod +x ./gradlew
          ls -la
          cat gradle.properties

      - name: Build APK
        run: |
          flutter build apk --debug
          ls -la build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tiforama-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
