name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Permet de déclencher manuellement le build

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Timeout après 20 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'
        channel: 'stable'
        cache: true

    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v

    - name: Clean project
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    - name: Verify project structure
      run: |
        ls -la
        ls -la lib/
        cat pubspec.yaml

    - name: Build APK (simplified)
      run: flutter build apk --release --no-tree-shake-icons --verbose

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tiforama-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
