name: Build APK Debug

on:
  workflow_dispatch:  # Seulement manuel pour debug

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Test basic functionality
      run: |
        echo "=== GitHub Actions Test ==="
        date
        pwd
        ls -la
        echo "=== Environment ==="
        env | sort

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List repository contents
      run: |
        echo "=== Repository Contents ==="
        ls -la
        echo "=== Pubspec check ==="
        if [ -f "pubspec.yaml" ]; then
          echo "pubspec.yaml found"
          head -20 pubspec.yaml
        else
          echo "ERROR: pubspec.yaml not found!"
        fi

    - name: Setup Java (basic)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Verify Java
      run: |
        java -version
        javac -version

    - name: Setup Flutter (basic)
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Verify Flutter basic
      run: |
        flutter --version
        which flutter
